"""Create credit card

Revision ID: 279ae3945907
Revises: 97035e8e22de
Create Date: 2021-06-30 11:23:45.793835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '279ae3945907'
down_revision = '97035e8e22de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expire_date', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('security_code', sa.String(length=3), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_cards')
    # ### end Alembic commands ###
